name: Deploy Airflow to Astronomer

on:
  push:
    branches: [main]
    paths:
      - "airflow/**"

env:
  ASTRO_API_TOKEN: ${{ secrets.ASTRONOMER_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Astro
        uses: astronomer/deploy-action@v0.12.0
        with:
          deployment-id: ${{ secrets.ASTRONOMER_DEPLOYMENT_ID }}
          root-folder: airflow
